### ISSUE TITLE
Difficulties starting the project locally

### ISSUE THREAD

**Issue by mindreframer** [Azarattum/CRStore#2]
Hey @Azarattum, I wanted to play with CRStore, but could not get it started with vite locally. 

This is the message:

```bash 
$  yarn dev
yarn run v1.22.19
$ vite dev
failed to load config from CRStore/vite.config.js
error when starting dev server:
ReferenceError: BroadcastChannel is not defined
    at database (file:///CRStore/vite.config.js.timestamp-1684107342218-0f51a313eeb19.mjs:470:19)
    at file:///CRStore/vite.config.js.timestamp-1684107342218-0f51a313eeb19.mjs:697:28
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Same message with pnpm. Do I need to configure something else to have `BroadcastChannel` available for vite to compile properly? Is this expected behaviour? 

Cheers and have a good Monday, 
Roman

**Comment by Azarattum** [comment]
Thanks for your interest in the project @mindreframer! What version of node are you using? BroadcastChannel should be available natively in the latest ones. I've tested 18+.

However I think this shouldn't be a requirement. I will change the code to use BroadcastChannel only if it's available.

**Comment by mindreframer** [comment]
@Azarattum Thank you for providing such an mature example of using cr_sqlite with Svelte! 

Node version: I was using v16.15.0, but I'll try it with 18+. Man, that stuff is changing so fast... 

Thanks for considering to remove the dependency on BroadcastChannel for server. 

Have a good day!

**Comment by Azarattum** [comment]
@mindreframer, should be fixed with https://github.com/Azarattum/CRStore/commit/db687763b18045644b94e6a77eb572e3748850b8. Try `0.14.7` version of the library.

**Comment by mindreframer** [comment]
Thanks, I will try it in couple hours and post, if it works with node < 18.0

**Comment by Azarattum** [comment]
Assuming everything worked out, I'm closing this
